services:
  - type: web
    plan: free
    name: X-URL-Uploader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Haniomry5/X-URL-Uploader.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DEF_THUMB_NAIL_VID_S 
        sync: false 
      - key: ADMIN 
        sync: false
      - key: AUTH_USERS 
        sync: false    
    autoDeploy: false 
